# @name user
GET http://localhost:3333/users 
  ?search=

###

POST http://localhost:3333/users 
Content-Type: application/json

{
  "name": "Vinicius Lima",
  "email": "vinicius@email.com.br"
}

###

PUT http://localhost:3333/users/64b0b3c1-cd5c-4fe5-8a1e-274c9d631d27
Content-Type: application/json

{
  "name": "Clarice Ramos",
  "email": "cla@email.com.br"
}

###

DELETE http://localhost:3333/users/ab5557ef-e508-47cb-b5d4-58c137320546